// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_limits.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const listAccountLimitObservations = `-- name: ListAccountLimitObservations :many
SELECT account_id, source_fingerprint, last_attempt_at, last_success_at, last_error_code, snapshot
FROM account_limit_observations
WHERE account_id = ANY($1::text[])
`

func (q *Queries) ListAccountLimitObservations(ctx context.Context, accountIds []string) ([]AccountLimitObservation, error) {
	rows, err := q.db.Query(ctx, listAccountLimitObservations, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountLimitObservation{}
	for rows.Next() {
		var i AccountLimitObservation
		if err := rows.Scan(
			&i.AccountID,
			&i.SourceFingerprint,
			&i.LastAttemptAt,
			&i.LastSuccessAt,
			&i.LastErrorCode,
			&i.Snapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccountLimitObservation = `-- name: UpsertAccountLimitObservation :exec
INSERT INTO account_limit_observations (
    account_id, source_fingerprint, last_attempt_at, last_success_at, last_error_code, snapshot
) VALUES (
    $1, $2, $3,
    CASE WHEN $4::text IS NULL THEN $3::timestamptz ELSE NULL END,
    $4::text, $5::jsonb
)
ON CONFLICT (account_id, source_fingerprint) DO UPDATE SET
    last_attempt_at = EXCLUDED.last_attempt_at,
    last_success_at = COALESCE(EXCLUDED.last_success_at, account_limit_observations.last_success_at),
    last_error_code = EXCLUDED.last_error_code,
    snapshot = COALESCE(EXCLUDED.snapshot, account_limit_observations.snapshot)
WHERE account_limit_observations.last_attempt_at < EXCLUDED.last_attempt_at
`

type UpsertAccountLimitObservationParams struct {
	AccountID         string          `json:"account_id"`
	SourceFingerprint string          `json:"source_fingerprint"`
	ObservedAt        time.Time       `json:"observed_at"`
	ErrorCode         *string         `json:"error_code"`
	Snapshot          json.RawMessage `json:"snapshot"`
}

func (q *Queries) UpsertAccountLimitObservation(ctx context.Context, arg UpsertAccountLimitObservationParams) error {
	_, err := q.db.Exec(ctx, upsertAccountLimitObservation,
		arg.AccountID,
		arg.SourceFingerprint,
		arg.ObservedAt,
		arg.ErrorCode,
		arg.Snapshot,
	)
	return err
}
