// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"
	"time"
)

const analyticsActiveSessions = `-- name: AnalyticsActiveSessions :one
SELECT COUNT(*)::bigint FROM runs r
JOIN sessions s ON s.id = r.session_id
WHERE r.status IN ('accepted', 'starting', 'running', 'cancelling', 'finalizing')
  AND ($1::text IS NULL OR s.namespace = $1::text)
`

func (q *Queries) AnalyticsActiveSessions(ctx context.Context, namespace *string) (int64, error) {
	row := q.db.QueryRow(ctx, analyticsActiveSessions, namespace)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const analyticsAsOf = `-- name: AnalyticsAsOf :one
SELECT transaction_timestamp()::timestamptz AS as_of
`

func (q *Queries) AnalyticsAsOf(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, analyticsAsOf)
	var as_of time.Time
	err := row.Scan(&as_of)
	return as_of, err
}
