// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hooks.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/orpheus-agents/orpheus/internal/session"
)

const getHookExecution = `-- name: GetHookExecution :one
SELECT id, session_id, run_id, name, status, started_at, deadline_at, cancel_attempted_at, stop_reason, finished_at, exit_code, signal, output, output_completeness, truncation_reason, error, kill_attempted_at, start_attempts FROM hook_executions WHERE run_id = $1 AND name = $2
`

type GetHookExecutionParams struct {
	RunID uuid.UUID `json:"run_id"`
	Name  string    `json:"name"`
}

func (q *Queries) GetHookExecution(ctx context.Context, arg GetHookExecutionParams) (HookExecution, error) {
	row := q.db.QueryRow(ctx, getHookExecution, arg.RunID, arg.Name)
	var i HookExecution
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.DeadlineAt,
		&i.CancelAttemptedAt,
		&i.StopReason,
		&i.FinishedAt,
		&i.ExitCode,
		&i.Signal,
		&i.Output,
		&i.OutputCompleteness,
		&i.TruncationReason,
		&i.Error,
		&i.KillAttemptedAt,
		&i.StartAttempts,
	)
	return i, err
}

const hookExecutions = `-- name: HookExecutions :many
SELECT id, session_id, run_id, name, status, started_at, deadline_at, cancel_attempted_at, stop_reason, finished_at, exit_code, signal, output, output_completeness, truncation_reason, error, kill_attempted_at, start_attempts FROM hook_executions WHERE run_id = $1 ORDER BY
  CASE name WHEN 'after_create' THEN 1 WHEN 'before_run' THEN 2 WHEN 'after_run' THEN 3 ELSE 4 END
`

func (q *Queries) HookExecutions(ctx context.Context, runID uuid.UUID) ([]HookExecution, error) {
	rows, err := q.db.Query(ctx, hookExecutions, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HookExecution{}
	for rows.Next() {
		var i HookExecution
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.DeadlineAt,
			&i.CancelAttemptedAt,
			&i.StopReason,
			&i.FinishedAt,
			&i.ExitCode,
			&i.Signal,
			&i.Output,
			&i.OutputCompleteness,
			&i.TruncationReason,
			&i.Error,
			&i.KillAttemptedAt,
			&i.StartAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hookExecutionsForRuns = `-- name: HookExecutionsForRuns :many
SELECT id, session_id, run_id, name, status, started_at, deadline_at, cancel_attempted_at, stop_reason, finished_at, exit_code, signal, output, output_completeness, truncation_reason, error, kill_attempted_at, start_attempts FROM hook_executions WHERE run_id = ANY($1::uuid[]) ORDER BY run_id,
  CASE name WHEN 'after_create' THEN 1 WHEN 'before_run' THEN 2 WHEN 'after_run' THEN 3 ELSE 4 END
`

func (q *Queries) HookExecutionsForRuns(ctx context.Context, runIds []uuid.UUID) ([]HookExecution, error) {
	rows, err := q.db.Query(ctx, hookExecutionsForRuns, runIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HookExecution{}
	for rows.Next() {
		var i HookExecution
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.DeadlineAt,
			&i.CancelAttemptedAt,
			&i.StopReason,
			&i.FinishedAt,
			&i.ExitCode,
			&i.Signal,
			&i.Output,
			&i.OutputCompleteness,
			&i.TruncationReason,
			&i.Error,
			&i.KillAttemptedAt,
			&i.StartAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHookExecution = `-- name: InsertHookExecution :exec
INSERT INTO hook_executions (id,session_id,run_id,name,status)
VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (run_id,name) DO NOTHING
`

type InsertHookExecutionParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
	RunID     uuid.UUID `json:"run_id"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
}

func (q *Queries) InsertHookExecution(ctx context.Context, arg InsertHookExecutionParams) error {
	_, err := q.db.Exec(ctx, insertHookExecution,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.Name,
		arg.Status,
	)
	return err
}

const saveHookExecution = `-- name: SaveHookExecution :exec
UPDATE hook_executions SET
  status = $2, started_at = $3, deadline_at = $4, cancel_attempted_at = $5,
  kill_attempted_at = $6, start_attempts = $7,
  finished_at = $8, exit_code = $9, signal = $10, output = $11,
  output_completeness = $12, truncation_reason = $13, error = $14,
  stop_reason = $15
WHERE id = $1
`

type SaveHookExecutionParams struct {
	ID                 uuid.UUID       `json:"id"`
	Status             string          `json:"status"`
	StartedAt          *time.Time      `json:"started_at"`
	DeadlineAt         *time.Time      `json:"deadline_at"`
	CancelAttemptedAt  *time.Time      `json:"cancel_attempted_at"`
	KillAttemptedAt    *time.Time      `json:"kill_attempted_at"`
	StartAttempts      int             `json:"start_attempts"`
	FinishedAt         *time.Time      `json:"finished_at"`
	ExitCode           *int            `json:"exit_code"`
	Signal             *int            `json:"signal"`
	Output             json.RawMessage `json:"output"`
	OutputCompleteness string          `json:"output_completeness"`
	TruncationReason   *string         `json:"truncation_reason"`
	Error              *session.Error  `json:"error"`
	StopReason         *string         `json:"stop_reason"`
}

func (q *Queries) SaveHookExecution(ctx context.Context, arg SaveHookExecutionParams) error {
	_, err := q.db.Exec(ctx, saveHookExecution,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.DeadlineAt,
		arg.CancelAttemptedAt,
		arg.KillAttemptedAt,
		arg.StartAttempts,
		arg.FinishedAt,
		arg.ExitCode,
		arg.Signal,
		arg.Output,
		arg.OutputCompleteness,
		arg.TruncationReason,
		arg.Error,
		arg.StopReason,
	)
	return err
}

const skipPendingHooks = `-- name: SkipPendingHooks :exec
UPDATE hook_executions SET status = 'skipped', finished_at = now()
WHERE run_id = $1 AND status = 'pending'
`

func (q *Queries) SkipPendingHooks(ctx context.Context, runID uuid.UUID) error {
	_, err := q.db.Exec(ctx, skipPendingHooks, runID)
	return err
}

const successfulAfterCreate = `-- name: SuccessfulAfterCreate :one
SELECT EXISTS (
  SELECT 1 FROM hook_executions WHERE session_id = $1 AND name = 'after_create' AND status = 'completed'
)
`

func (q *Queries) SuccessfulAfterCreate(ctx context.Context, sessionID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, successfulAfterCreate, sessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
