// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/skillum-ai/orpheus/internal/session"
)

type IdempotencyKey struct {
	Operation   string    `json:"operation"`
	Resource    string    `json:"resource"`
	Key         uuid.UUID `json:"key"`
	Fingerprint string    `json:"fingerprint"`
	SessionID   uuid.UUID `json:"session_id"`
	RunID       uuid.UUID `json:"run_id"`
	MessageID   uuid.UUID `json:"message_id"`
}

type Message struct {
	ID                 uuid.UUID         `json:"id"`
	SessionID          uuid.UUID         `json:"session_id"`
	RunID              uuid.UUID         `json:"run_id"`
	Role               string            `json:"role"`
	Kind               *string           `json:"kind"`
	Text               string            `json:"text"`
	DeliveryStatus     *string           `json:"delivery_status"`
	DeliveryNumber     *int              `json:"delivery_number"`
	Error              *session.Error    `json:"error"`
	NativeKey          *string           `json:"native_key"`
	RegisteredSequence int64             `json:"registered_sequence"`
	Position           *session.Position `json:"position"`
	CreatedAt          time.Time         `json:"created_at"`
	ExternalKey        *string           `json:"external_key"`
}

type Operation struct {
	ID          uuid.UUID       `json:"id"`
	SessionID   uuid.UUID       `json:"session_id"`
	RunID       *uuid.UUID      `json:"run_id"`
	MessageID   *uuid.UUID      `json:"message_id"`
	Kind        string          `json:"kind"`
	Status      string          `json:"status"`
	Parameters  json.RawMessage `json:"parameters"`
	Result      json.RawMessage `json:"result"`
	AttemptedAt *time.Time      `json:"attempted_at"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Run struct {
	ID                 uuid.UUID      `json:"id"`
	SessionID          uuid.UUID      `json:"session_id"`
	Number             int            `json:"number"`
	Status             session.Status `json:"status"`
	Observation        *string        `json:"observation"`
	CreatedAt          time.Time      `json:"created_at"`
	ExecutionStartedAt *time.Time     `json:"execution_started_at"`
	DeadlineAt         *time.Time     `json:"deadline_at"`
	FinishedAt         *time.Time     `json:"finished_at"`
	CancelRequestedAt  *time.Time     `json:"cancel_requested_at"`
	CancelAttemptedAt  *time.Time     `json:"cancel_attempted_at"`
	StopReason         *string        `json:"stop_reason"`
	StopMethod         *string        `json:"stop_method"`
	Error              *session.Error `json:"error"`
	NativeTurnID       *string        `json:"native_turn_id"`
	NextDeliveryNumber int            `json:"next_delivery_number"`
	FinalMessageID     *uuid.UUID     `json:"final_message_id"`
	InputFingerprint   *string        `json:"input_fingerprint"`
	EnvCiphertext      *string        `json:"env_ciphertext"`
	EnvNames           []string       `json:"env_names"`
	EnvFrom            []string       `json:"env_from"`
}

type Session struct {
	ID                    uuid.UUID                     `json:"id"`
	CreatedAt             time.Time                     `json:"created_at"`
	Configuration         session.ResolvedConfiguration `json:"configuration"`
	EnvCiphertext         *string                       `json:"env_ciphertext"`
	SandboxState          string                        `json:"sandbox_state"`
	SandboxLastKnownState *string                       `json:"sandbox_last_known_state"`
	SandboxError          *session.Error                `json:"sandbox_error"`
	SandboxID             *string                       `json:"sandbox_id"`
	ProcessID             *int                          `json:"process_id"`
	LaunchID              *uuid.UUID                    `json:"launch_id"`
	ThreadID              *string                       `json:"thread_id"`
	HistoryPath           *string                       `json:"history_path"`
	HistoryOffset         int64                         `json:"history_offset"`
	Workspace             *string                       `json:"workspace"`
	HarnessHome           *string                       `json:"harness_home"`
	SlotReserved          bool                          `json:"slot_reserved"`
	NextRunNumber         int                           `json:"next_run_number"`
	NextEventSequence     int64                         `json:"next_event_sequence"`
	Namespace             *string                       `json:"namespace"`
	ExternalKey           *string                       `json:"external_key"`
}

type SessionEvent struct {
	SessionID uuid.UUID       `json:"session_id"`
	Sequence  int64           `json:"sequence"`
	Type      string          `json:"type"`
	CreatedAt time.Time       `json:"created_at"`
	Data      json.RawMessage `json:"data"`
}

type ToolCall struct {
	ID                 uuid.UUID         `json:"id"`
	SessionID          uuid.UUID         `json:"session_id"`
	RunID              uuid.UUID         `json:"run_id"`
	Name               string            `json:"name"`
	Input              json.RawMessage   `json:"input"`
	Status             string            `json:"status"`
	Result             json.RawMessage   `json:"result"`
	ResultDigest       string            `json:"result_digest"`
	OutputCompleteness string            `json:"output_completeness"`
	TruncationReason   *string           `json:"truncation_reason"`
	NativeKey          *string           `json:"native_key"`
	RegisteredSequence int64             `json:"registered_sequence"`
	Position           *session.Position `json:"position"`
	CreatedAt          time.Time         `json:"created_at"`
}
