// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations AS o(id, session_id, run_id, message_id, kind, parameters)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING o.id, o.session_id, o.run_id, o.message_id, o.kind, o.status, o.parameters, o.result, o.attempted_at, o.created_at
`

type CreateOperationParams struct {
	ID         uuid.UUID       `json:"id"`
	SessionID  uuid.UUID       `json:"session_id"`
	RunID      *uuid.UUID      `json:"run_id"`
	MessageID  *uuid.UUID      `json:"message_id"`
	Kind       string          `json:"kind"`
	Parameters json.RawMessage `json:"parameters"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.MessageID,
		arg.Kind,
		arg.Parameters,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.MessageID,
		&i.Kind,
		&i.Status,
		&i.Parameters,
		&i.Result,
		&i.AttemptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findOperation = `-- name: FindOperation :one
SELECT o.id, o.session_id, o.run_id, o.message_id, o.kind, o.status, o.parameters, o.result, o.attempted_at, o.created_at
FROM operations o
WHERE session_id = $1 AND kind = $2 AND run_id IS NOT DISTINCT
FROM $3::uuid AND message_id IS NOT DISTINCT
FROM $4::uuid
ORDER BY created_at DESC
LIMIT 1
`

type FindOperationParams struct {
	SessionID uuid.UUID  `json:"session_id"`
	Kind      string     `json:"kind"`
	RunID     *uuid.UUID `json:"run_id"`
	MessageID *uuid.UUID `json:"message_id"`
}

func (q *Queries) FindOperation(ctx context.Context, arg FindOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, findOperation,
		arg.SessionID,
		arg.Kind,
		arg.RunID,
		arg.MessageID,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.MessageID,
		&i.Kind,
		&i.Status,
		&i.Parameters,
		&i.Result,
		&i.AttemptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOperation = `-- name: GetOperation :one
SELECT o.id, o.session_id, o.run_id, o.message_id, o.kind, o.status, o.parameters, o.result, o.attempted_at, o.created_at
FROM operations o
WHERE id = $1
`

func (q *Queries) GetOperation(ctx context.Context, id uuid.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.MessageID,
		&i.Kind,
		&i.Status,
		&i.Parameters,
		&i.Result,
		&i.AttemptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionOperation = `-- name: GetSessionOperation :one
SELECT o.id, o.session_id, o.run_id, o.message_id, o.kind, o.status, o.parameters, o.result, o.attempted_at, o.created_at
FROM operations o
WHERE id = $1 AND session_id = $2
`

type GetSessionOperationParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) GetSessionOperation(ctx context.Context, arg GetSessionOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, getSessionOperation, arg.ID, arg.SessionID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.MessageID,
		&i.Kind,
		&i.Status,
		&i.Parameters,
		&i.Result,
		&i.AttemptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const lastTerminalRun = `-- name: LastTerminalRun :one
SELECT r.id, r.session_id, r.number, r.status, r.observation, r.created_at, r.execution_started_at, r.deadline_at, r.finished_at, r.cancel_requested_at, r.cancel_attempted_at, r.stop_reason, r.stop_method, r.error, r.native_turn_id, r.next_delivery_number, r.final_message_id
FROM runs r
WHERE session_id = $1 AND status IN ('completed', 'failed', 'cancelled')
ORDER BY number DESC
LIMIT 1
`

func (q *Queries) LastTerminalRun(ctx context.Context, sessionID uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, lastTerminalRun, sessionID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Number,
		&i.Status,
		&i.Observation,
		&i.CreatedAt,
		&i.ExecutionStartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
		&i.CancelAttemptedAt,
		&i.StopReason,
		&i.StopMethod,
		&i.Error,
		&i.NativeTurnID,
		&i.NextDeliveryNumber,
		&i.FinalMessageID,
	)
	return i, err
}

const latestAttempt = `-- name: LatestAttempt :one
SELECT o.id, o.session_id, o.run_id, o.message_id, o.kind, o.status, o.parameters, o.result, o.attempted_at, o.created_at
FROM operations o
WHERE session_id = $1 AND kind = $2 AND status IN ('sending', 'uncertain', 'confirmed')
ORDER BY created_at DESC
LIMIT 1
`

type LatestAttemptParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Kind      string    `json:"kind"`
}

func (q *Queries) LatestAttempt(ctx context.Context, arg LatestAttemptParams) (Operation, error) {
	row := q.db.QueryRow(ctx, latestAttempt, arg.SessionID, arg.Kind)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.MessageID,
		&i.Kind,
		&i.Status,
		&i.Parameters,
		&i.Result,
		&i.AttemptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const previousExecutedRun = `-- name: PreviousExecutedRun :one
SELECT r.id, r.session_id, r.number, r.status, r.observation, r.created_at, r.execution_started_at, r.deadline_at, r.finished_at, r.cancel_requested_at, r.cancel_attempted_at, r.stop_reason, r.stop_method, r.error, r.native_turn_id, r.next_delivery_number, r.final_message_id
FROM runs r
WHERE session_id = $1 AND number<$2 AND (execution_started_at IS NOT NULL OR error->>'code' = 'authentication_failed')
ORDER BY number DESC
LIMIT 1
`

type PreviousExecutedRunParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Number    int       `json:"number"`
}

func (q *Queries) PreviousExecutedRun(ctx context.Context, arg PreviousExecutedRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, previousExecutedRun, arg.SessionID, arg.Number)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Number,
		&i.Status,
		&i.Observation,
		&i.CreatedAt,
		&i.ExecutionStartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
		&i.CancelAttemptedAt,
		&i.StopReason,
		&i.StopMethod,
		&i.Error,
		&i.NativeTurnID,
		&i.NextDeliveryNumber,
		&i.FinalMessageID,
	)
	return i, err
}

const saveOperation = `-- name: SaveOperation :exec
UPDATE operations
SET status = $2,
    result = $3,
    attempted_at = $4
WHERE id = $1
`

type SaveOperationParams struct {
	ID          uuid.UUID       `json:"id"`
	Status      string          `json:"status"`
	Result      json.RawMessage `json:"result"`
	AttemptedAt *time.Time      `json:"attempted_at"`
}

func (q *Queries) SaveOperation(ctx context.Context, arg SaveOperationParams) error {
	_, err := q.db.Exec(ctx, saveOperation,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.AttemptedAt,
	)
	return err
}
