// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const history = `-- name: History :many
WITH objects AS (
   SELECT DISTINCT ON(type, data->>'id') type, data FROM session_events
   WHERE session_events.session_id = $7 AND sequence<=$8::bigint AND type IN ('message.updated', 'tool_call.updated')
   ORDER BY type, data->>'id', sequence DESC
  ), positioned AS (
   SELECT objects.type, objects.data, runs.number AS rn,
    CASE WHEN objects.data->'position' = 'null'::jsonb THEN 1 ELSE 0 END AS unknown,
    COALESCE((objects.data->'position'->>'item_index')::bigint,0)::bigint AS idx,
    (objects.data->>'registered_sequence')::bigint AS seq
   FROM objects JOIN runs ON runs.id = (objects.data->>'run_id')::uuid
   WHERE ($9::uuid IS NULL OR runs.id = $9::uuid)
  ) SELECT type, data, rn, unknown, idx, seq FROM positioned
  WHERE ($1::boolean OR (rn, unknown, idx, seq)>($2::bigint, $3::bigint, $4::bigint, $5::bigint)) ORDER BY rn, unknown, idx, seq LIMIT $6::int
`

type HistoryParams struct {
	FirstPage     bool       `json:"first_page"`
	AfterRun      int64      `json:"after_run"`
	AfterUnknown  int64      `json:"after_unknown"`
	AfterIndex    int64      `json:"after_index"`
	AfterSequence int64      `json:"after_sequence"`
	PageLimit     int        `json:"page_limit"`
	SessionID     uuid.UUID  `json:"session_id"`
	Watermark     int64      `json:"watermark"`
	RunID         *uuid.UUID `json:"run_id"`
}

type HistoryRow struct {
	Type    string          `json:"type"`
	Data    json.RawMessage `json:"data"`
	Rn      int             `json:"rn"`
	Unknown int32           `json:"unknown"`
	Idx     int64           `json:"idx"`
	Seq     int64           `json:"seq"`
}

func (q *Queries) History(ctx context.Context, arg HistoryParams) ([]HistoryRow, error) {
	rows, err := q.db.Query(ctx, history,
		arg.FirstPage,
		arg.AfterRun,
		arg.AfterUnknown,
		arg.AfterIndex,
		arg.AfterSequence,
		arg.PageLimit,
		arg.SessionID,
		arg.Watermark,
		arg.RunID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoryRow{}
	for rows.Next() {
		var i HistoryRow
		if err := rows.Scan(
			&i.Type,
			&i.Data,
			&i.Rn,
			&i.Unknown,
			&i.Idx,
			&i.Seq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT sequence::text, session_id, type, created_at, data FROM session_events WHERE session_id = $1 AND sequence>$2 ORDER BY sequence LIMIT $3::int
`

type ListEventsParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Sequence  int64     `json:"sequence"`
	PageLimit int       `json:"page_limit"`
}

type ListEventsRow struct {
	Sequence  string          `json:"sequence"`
	SessionID uuid.UUID       `json:"session_id"`
	Type      string          `json:"type"`
	CreatedAt time.Time       `json:"created_at"`
	Data      json.RawMessage `json:"data"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.SessionID, arg.Sequence, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsRow{}
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.Sequence,
			&i.SessionID,
			&i.Type,
			&i.CreatedAt,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT r.id, r.session_id, r.number, r.status, r.observation, r.created_at, r.execution_started_at, r.deadline_at, r.finished_at, r.cancel_requested_at, r.cancel_attempted_at, r.stop_reason, r.stop_method, r.error, r.native_turn_id, r.next_delivery_number, r.final_message_id FROM runs r WHERE session_id = $1 AND number>$2 ORDER BY number LIMIT $3::int
`

type ListRunsParams struct {
	SessionID uuid.UUID `json:"session_id"`
	Number    int       `json:"number"`
	PageLimit int       `json:"page_limit"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.SessionID, arg.Number, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Number,
			&i.Status,
			&i.Observation,
			&i.CreatedAt,
			&i.ExecutionStartedAt,
			&i.DeadlineAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
			&i.CancelAttemptedAt,
			&i.StopReason,
			&i.StopMethod,
			&i.Error,
			&i.NativeTurnID,
			&i.NextDeliveryNumber,
			&i.FinalMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.id, s.created_at, s.configuration, s.env_ciphertext, s.sandbox_state, s.sandbox_last_known_state, s.sandbox_error, s.sandbox_id, s.process_id, s.launch_id, s.thread_id, s.history_path, s.history_offset, s.workspace, s.harness_home, s.slot_reserved, s.next_run_number, s.next_event_sequence FROM sessions s WHERE ($1::boolean OR (created_at, id)>($2::timestamptz, $3::uuid)) ORDER BY created_at, id LIMIT $4::int
`

type ListSessionsParams struct {
	FirstPage bool      `json:"first_page"`
	AfterDate time.Time `json:"after_date"`
	AfterID   uuid.UUID `json:"after_id"`
	PageLimit int       `json:"page_limit"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.FirstPage,
		arg.AfterDate,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Configuration,
			&i.EnvCiphertext,
			&i.SandboxState,
			&i.SandboxLastKnownState,
			&i.SandboxError,
			&i.SandboxID,
			&i.ProcessID,
			&i.LaunchID,
			&i.ThreadID,
			&i.HistoryPath,
			&i.HistoryOffset,
			&i.Workspace,
			&i.HarnessHome,
			&i.SlotReserved,
			&i.NextRunNumber,
			&i.NextEventSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
