// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/skillum-ai/orpheus/internal/session"
)

const reconcileMessages = `-- name: ReconcileMessages :many
SELECT id, session_id, run_id, role, kind, text, delivery_status, delivery_number, error, native_key, registered_sequence, position, created_at
FROM messages
WHERE session_id = $1 AND (native_key = ANY($2::text[]) OR native_key IS NULL)
ORDER BY delivery_number, registered_sequence
`

type ReconcileMessagesParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	NativeKeys []string  `json:"native_keys"`
}

func (q *Queries) ReconcileMessages(ctx context.Context, arg ReconcileMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, reconcileMessages, arg.SessionID, arg.NativeKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Role,
			&i.Kind,
			&i.Text,
			&i.DeliveryStatus,
			&i.DeliveryNumber,
			&i.Error,
			&i.NativeKey,
			&i.RegisteredSequence,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileOperations = `-- name: ReconcileOperations :many
SELECT o.id, o.session_id, o.run_id, o.message_id, o.kind, o.status, o.parameters, o.result, o.attempted_at, o.created_at
FROM operations o
WHERE session_id = $1 AND kind IN ('start', 'steer') AND run_id = ANY($2::uuid[])
ORDER BY created_at
`

type ReconcileOperationsParams struct {
	SessionID uuid.UUID   `json:"session_id"`
	RunIds    []uuid.UUID `json:"run_ids"`
}

func (q *Queries) ReconcileOperations(ctx context.Context, arg ReconcileOperationsParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, reconcileOperations, arg.SessionID, arg.RunIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.MessageID,
			&i.Kind,
			&i.Status,
			&i.Parameters,
			&i.Result,
			&i.AttemptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileRuns = `-- name: ReconcileRuns :many
SELECT r.id, r.session_id, r.number, r.status, r.observation, r.created_at, r.execution_started_at, r.deadline_at, r.finished_at, r.cancel_requested_at, r.cancel_attempted_at, r.stop_reason, r.stop_method, r.error, r.native_turn_id, r.next_delivery_number, r.final_message_id
FROM runs r
WHERE session_id = $1 AND (status IN ('accepted', 'starting', 'running', 'cancelling') OR native_turn_id = ANY($2::text[]))
ORDER BY number
`

type ReconcileRunsParams struct {
	SessionID uuid.UUID `json:"session_id"`
	TurnIds   []string  `json:"turn_ids"`
}

func (q *Queries) ReconcileRuns(ctx context.Context, arg ReconcileRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, reconcileRuns, arg.SessionID, arg.TurnIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Number,
			&i.Status,
			&i.Observation,
			&i.CreatedAt,
			&i.ExecutionStartedAt,
			&i.DeadlineAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
			&i.CancelAttemptedAt,
			&i.StopReason,
			&i.StopMethod,
			&i.Error,
			&i.NativeTurnID,
			&i.NextDeliveryNumber,
			&i.FinalMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toolMetadata = `-- name: ToolMetadata :many
SELECT id, session_id, run_id, name, input, status, output_completeness, truncation_reason, native_key, registered_sequence, position, created_at,(result IS NOT NULL)::boolean AS has_result, result_digest
FROM tool_calls
WHERE session_id = $1 AND native_key = ANY($2::text[])
`

type ToolMetadataParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	NativeKeys []string  `json:"native_keys"`
}

type ToolMetadataRow struct {
	ID                 uuid.UUID         `json:"id"`
	SessionID          uuid.UUID         `json:"session_id"`
	RunID              uuid.UUID         `json:"run_id"`
	Name               string            `json:"name"`
	Input              json.RawMessage   `json:"input"`
	Status             string            `json:"status"`
	OutputCompleteness string            `json:"output_completeness"`
	TruncationReason   *string           `json:"truncation_reason"`
	NativeKey          *string           `json:"native_key"`
	RegisteredSequence int64             `json:"registered_sequence"`
	Position           *session.Position `json:"position"`
	CreatedAt          time.Time         `json:"created_at"`
	HasResult          bool              `json:"has_result"`
	ResultDigest       string            `json:"result_digest"`
}

func (q *Queries) ToolMetadata(ctx context.Context, arg ToolMetadataParams) ([]ToolMetadataRow, error) {
	rows, err := q.db.Query(ctx, toolMetadata, arg.SessionID, arg.NativeKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolMetadataRow{}
	for rows.Next() {
		var i ToolMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Name,
			&i.Input,
			&i.Status,
			&i.OutputCompleteness,
			&i.TruncationReason,
			&i.NativeKey,
			&i.RegisteredSequence,
			&i.Position,
			&i.CreatedAt,
			&i.HasResult,
			&i.ResultDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toolsByID = `-- name: ToolsByID :many
SELECT t.id, t.session_id, t.run_id, t.name, t.input, t.status, t.result, t.result_digest, t.output_completeness, t.truncation_reason, t.native_key, t.registered_sequence, t.position, t.created_at
FROM tool_calls t
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ToolsByID(ctx context.Context, ids []uuid.UUID) ([]ToolCall, error) {
	rows, err := q.db.Query(ctx, toolsByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Name,
			&i.Input,
			&i.Status,
			&i.Result,
			&i.ResultDigest,
			&i.OutputCompleteness,
			&i.TruncationReason,
			&i.NativeKey,
			&i.RegisteredSequence,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
