// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/skillum-ai/orpheus/internal/session"
)

const activeRun = `-- name: ActiveRun :one
SELECT r.id, r.session_id, r.number, r.status, r.observation, r.created_at, r.execution_started_at, r.deadline_at, r.finished_at, r.cancel_requested_at, r.cancel_attempted_at, r.stop_reason, r.stop_method, r.error, r.native_turn_id, r.next_delivery_number, r.final_message_id, r.input_fingerprint, r.env_ciphertext, r.env_names, r.env_from, r.phase, r.agent_status, r.agent_error
FROM runs r
WHERE session_id = $1 AND status IN ('accepted', 'starting', 'running', 'cancelling', 'finalizing')
`

func (q *Queries) ActiveRun(ctx context.Context, sessionID uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, activeRun, sessionID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Number,
		&i.Status,
		&i.Observation,
		&i.CreatedAt,
		&i.ExecutionStartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
		&i.CancelAttemptedAt,
		&i.StopReason,
		&i.StopMethod,
		&i.Error,
		&i.NativeTurnID,
		&i.NextDeliveryNumber,
		&i.FinalMessageID,
		&i.InputFingerprint,
		&i.EnvCiphertext,
		&i.EnvNames,
		&i.EnvFrom,
		&i.Phase,
		&i.AgentStatus,
		&i.AgentError,
	)
	return i, err
}

const advisoryLock = `-- name: AdvisoryLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

func (q *Queries) AdvisoryLock(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, advisoryLock, lockKey)
	return err
}

const countReserved = `-- name: CountReserved :one
SELECT count(*)
FROM sessions
WHERE slot_reserved
`

func (q *Queries) CountReserved(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countReserved)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs AS r(id, session_id, number, input_fingerprint, env_ciphertext, env_names, env_from)
VALUES($1, $2, $3, $4, $5, $6, $7)
RETURNING r.id, r.session_id, r.number, r.status, r.observation, r.created_at, r.execution_started_at, r.deadline_at, r.finished_at, r.cancel_requested_at, r.cancel_attempted_at, r.stop_reason, r.stop_method, r.error, r.native_turn_id, r.next_delivery_number, r.final_message_id, r.input_fingerprint, r.env_ciphertext, r.env_names, r.env_from, r.phase, r.agent_status, r.agent_error
`

type CreateRunParams struct {
	ID               uuid.UUID `json:"id"`
	SessionID        uuid.UUID `json:"session_id"`
	Number           int       `json:"number"`
	InputFingerprint *string   `json:"input_fingerprint"`
	EnvCiphertext    *string   `json:"env_ciphertext"`
	EnvNames         []string  `json:"env_names"`
	EnvFrom          []string  `json:"env_from"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.SessionID,
		arg.Number,
		arg.InputFingerprint,
		arg.EnvCiphertext,
		arg.EnvNames,
		arg.EnvFrom,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Number,
		&i.Status,
		&i.Observation,
		&i.CreatedAt,
		&i.ExecutionStartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
		&i.CancelAttemptedAt,
		&i.StopReason,
		&i.StopMethod,
		&i.Error,
		&i.NativeTurnID,
		&i.NextDeliveryNumber,
		&i.FinalMessageID,
		&i.InputFingerprint,
		&i.EnvCiphertext,
		&i.EnvNames,
		&i.EnvFrom,
		&i.Phase,
		&i.AgentStatus,
		&i.AgentError,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions AS s(id, configuration, env_ciphertext, slot_reserved, namespace, external_key)
VALUES($1, $2, $3, false, $4, $5)
RETURNING s.id, s.created_at, s.configuration, s.env_ciphertext, s.sandbox_state, s.sandbox_last_known_state, s.sandbox_error, s.sandbox_id, s.process_id, s.launch_id, s.thread_id, s.history_path, s.history_offset, s.workspace, s.harness_home, s.slot_reserved, s.next_run_number, s.next_event_sequence, s.namespace, s.external_key
`

type CreateSessionParams struct {
	ID            uuid.UUID                     `json:"id"`
	Configuration session.ResolvedConfiguration `json:"configuration"`
	EnvCiphertext *string                       `json:"env_ciphertext"`
	Namespace     *string                       `json:"namespace"`
	ExternalKey   *string                       `json:"external_key"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.Configuration,
		arg.EnvCiphertext,
		arg.Namespace,
		arg.ExternalKey,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Configuration,
		&i.EnvCiphertext,
		&i.SandboxState,
		&i.SandboxLastKnownState,
		&i.SandboxError,
		&i.SandboxID,
		&i.ProcessID,
		&i.LaunchID,
		&i.ThreadID,
		&i.HistoryPath,
		&i.HistoryOffset,
		&i.Workspace,
		&i.HarnessHome,
		&i.SlotReserved,
		&i.NextRunNumber,
		&i.NextEventSequence,
		&i.Namespace,
		&i.ExternalKey,
	)
	return i, err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT fingerprint, session_id, run_id, message_id
FROM idempotency_keys
WHERE operation = $1 AND resource = $2 AND key = $3
`

type GetIdempotencyParams struct {
	Operation string    `json:"operation"`
	Resource  string    `json:"resource"`
	Key       uuid.UUID `json:"key"`
}

type GetIdempotencyRow struct {
	Fingerprint string    `json:"fingerprint"`
	SessionID   uuid.UUID `json:"session_id"`
	RunID       uuid.UUID `json:"run_id"`
	MessageID   uuid.UUID `json:"message_id"`
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (GetIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.Operation, arg.Resource, arg.Key)
	var i GetIdempotencyRow
	err := row.Scan(
		&i.Fingerprint,
		&i.SessionID,
		&i.RunID,
		&i.MessageID,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, run_id, role, kind, text, delivery_status, delivery_number, error, native_key, registered_sequence, position, created_at, external_key
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.Role,
		&i.Kind,
		&i.Text,
		&i.DeliveryStatus,
		&i.DeliveryNumber,
		&i.Error,
		&i.NativeKey,
		&i.RegisteredSequence,
		&i.Position,
		&i.CreatedAt,
		&i.ExternalKey,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT r.id, r.session_id, r.number, r.status, r.observation, r.created_at, r.execution_started_at, r.deadline_at, r.finished_at, r.cancel_requested_at, r.cancel_attempted_at, r.stop_reason, r.stop_method, r.error, r.native_turn_id, r.next_delivery_number, r.final_message_id, r.input_fingerprint, r.env_ciphertext, r.env_names, r.env_from, r.phase, r.agent_status, r.agent_error
FROM runs r
WHERE session_id = $1 AND id = $2
`

type GetRunParams struct {
	SessionID uuid.UUID `json:"session_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, arg.SessionID, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Number,
		&i.Status,
		&i.Observation,
		&i.CreatedAt,
		&i.ExecutionStartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
		&i.CancelAttemptedAt,
		&i.StopReason,
		&i.StopMethod,
		&i.Error,
		&i.NativeTurnID,
		&i.NextDeliveryNumber,
		&i.FinalMessageID,
		&i.InputFingerprint,
		&i.EnvCiphertext,
		&i.EnvNames,
		&i.EnvFrom,
		&i.Phase,
		&i.AgentStatus,
		&i.AgentError,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.created_at, s.configuration, s.env_ciphertext, s.sandbox_state, s.sandbox_last_known_state, s.sandbox_error, s.sandbox_id, s.process_id, s.launch_id, s.thread_id, s.history_path, s.history_offset, s.workspace, s.harness_home, s.slot_reserved, s.next_run_number, s.next_event_sequence, s.namespace, s.external_key
FROM sessions s
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Configuration,
		&i.EnvCiphertext,
		&i.SandboxState,
		&i.SandboxLastKnownState,
		&i.SandboxError,
		&i.SandboxID,
		&i.ProcessID,
		&i.LaunchID,
		&i.ThreadID,
		&i.HistoryPath,
		&i.HistoryOffset,
		&i.Workspace,
		&i.HarnessHome,
		&i.SlotReserved,
		&i.NextRunNumber,
		&i.NextEventSequence,
		&i.Namespace,
		&i.ExternalKey,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO session_events(session_id, sequence, type, data)
VALUES($1, $2, $3, $4)
`

type InsertEventParams struct {
	SessionID uuid.UUID       `json:"session_id"`
	Sequence  int64           `json:"sequence"`
	Type      string          `json:"type"`
	Data      json.RawMessage `json:"data"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.SessionID,
		arg.Sequence,
		arg.Type,
		arg.Data,
	)
	return err
}

const insertIdempotency = `-- name: InsertIdempotency :exec
INSERT INTO idempotency_keys(operation, resource, key, fingerprint, session_id, run_id, message_id)
VALUES($1, $2, $3, $4, $5, $6, $7)
`

type InsertIdempotencyParams struct {
	Operation   string    `json:"operation"`
	Resource    string    `json:"resource"`
	Key         uuid.UUID `json:"key"`
	Fingerprint string    `json:"fingerprint"`
	SessionID   uuid.UUID `json:"session_id"`
	RunID       uuid.UUID `json:"run_id"`
	MessageID   uuid.UUID `json:"message_id"`
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotency,
		arg.Operation,
		arg.Resource,
		arg.Key,
		arg.Fingerprint,
		arg.SessionID,
		arg.RunID,
		arg.MessageID,
	)
	return err
}

const latestRun = `-- name: LatestRun :one
SELECT r.id, r.session_id, r.number, r.status, r.observation, r.created_at, r.execution_started_at, r.deadline_at, r.finished_at, r.cancel_requested_at, r.cancel_attempted_at, r.stop_reason, r.stop_method, r.error, r.native_turn_id, r.next_delivery_number, r.final_message_id, r.input_fingerprint, r.env_ciphertext, r.env_names, r.env_from, r.phase, r.agent_status, r.agent_error
FROM runs r
WHERE session_id = $1
ORDER BY number DESC
LIMIT 1
`

func (q *Queries) LatestRun(ctx context.Context, sessionID uuid.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, latestRun, sessionID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Number,
		&i.Status,
		&i.Observation,
		&i.CreatedAt,
		&i.ExecutionStartedAt,
		&i.DeadlineAt,
		&i.FinishedAt,
		&i.CancelRequestedAt,
		&i.CancelAttemptedAt,
		&i.StopReason,
		&i.StopMethod,
		&i.Error,
		&i.NativeTurnID,
		&i.NextDeliveryNumber,
		&i.FinalMessageID,
		&i.InputFingerprint,
		&i.EnvCiphertext,
		&i.EnvNames,
		&i.EnvFrom,
		&i.Phase,
		&i.AgentStatus,
		&i.AgentError,
	)
	return i, err
}

const lockSession = `-- name: LockSession :one
SELECT s.id, s.created_at, s.configuration, s.env_ciphertext, s.sandbox_state, s.sandbox_last_known_state, s.sandbox_error, s.sandbox_id, s.process_id, s.launch_id, s.thread_id, s.history_path, s.history_offset, s.workspace, s.harness_home, s.slot_reserved, s.next_run_number, s.next_event_sequence, s.namespace, s.external_key
FROM sessions s
WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, lockSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Configuration,
		&i.EnvCiphertext,
		&i.SandboxState,
		&i.SandboxLastKnownState,
		&i.SandboxError,
		&i.SandboxID,
		&i.ProcessID,
		&i.LaunchID,
		&i.ThreadID,
		&i.HistoryPath,
		&i.HistoryOffset,
		&i.Workspace,
		&i.HarnessHome,
		&i.SlotReserved,
		&i.NextRunNumber,
		&i.NextEventSequence,
		&i.Namespace,
		&i.ExternalKey,
	)
	return i, err
}

const messages = `-- name: Messages :many
SELECT id, session_id, run_id, role, kind, text, delivery_status, delivery_number, error, native_key, registered_sequence, position, created_at, external_key
FROM messages
WHERE run_id = $1
ORDER BY delivery_number, registered_sequence
`

func (q *Queries) Messages(ctx context.Context, runID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, messages, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Role,
			&i.Kind,
			&i.Text,
			&i.DeliveryStatus,
			&i.DeliveryNumber,
			&i.Error,
			&i.NativeKey,
			&i.RegisteredSequence,
			&i.Position,
			&i.CreatedAt,
			&i.ExternalKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesByIDs = `-- name: MessagesByIDs :many
SELECT id, session_id, run_id, role, kind, text, delivery_status, delivery_number, error, native_key, registered_sequence, position, created_at, external_key
FROM messages
WHERE id = ANY($1::uuid[])
`

func (q *Queries) MessagesByIDs(ctx context.Context, messageIds []uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, messagesByIDs, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RunID,
			&i.Role,
			&i.Kind,
			&i.Text,
			&i.DeliveryStatus,
			&i.DeliveryNumber,
			&i.Error,
			&i.NativeKey,
			&i.RegisteredSequence,
			&i.Position,
			&i.CreatedAt,
			&i.ExternalKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reservedSessions = `-- name: ReservedSessions :many
SELECT id
FROM sessions
WHERE slot_reserved
`

func (q *Queries) ReservedSessions(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, reservedSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveRun = `-- name: SaveRun :exec
UPDATE runs
SET status = $2,
    observation = $3,
    execution_started_at = $4,
    deadline_at = $5,
    finished_at = $6,
    cancel_requested_at = $7,
    cancel_attempted_at = $8,
    stop_reason = $9,
    stop_method = $10,
    error = $11,
    native_turn_id = $12,
    next_delivery_number = $13,
    final_message_id = $14,
    phase = $15,
    agent_status = $16,
    agent_error = $17
WHERE id = $1
`

type SaveRunParams struct {
	ID                 uuid.UUID       `json:"id"`
	Status             session.Status  `json:"status"`
	Observation        *string         `json:"observation"`
	ExecutionStartedAt *time.Time      `json:"execution_started_at"`
	DeadlineAt         *time.Time      `json:"deadline_at"`
	FinishedAt         *time.Time      `json:"finished_at"`
	CancelRequestedAt  *time.Time      `json:"cancel_requested_at"`
	CancelAttemptedAt  *time.Time      `json:"cancel_attempted_at"`
	StopReason         *string         `json:"stop_reason"`
	StopMethod         *string         `json:"stop_method"`
	Error              *session.Error  `json:"error"`
	NativeTurnID       *string         `json:"native_turn_id"`
	NextDeliveryNumber int             `json:"next_delivery_number"`
	FinalMessageID     *uuid.UUID      `json:"final_message_id"`
	Phase              *string         `json:"phase"`
	AgentStatus        *session.Status `json:"agent_status"`
	AgentError         *session.Error  `json:"agent_error"`
}

func (q *Queries) SaveRun(ctx context.Context, arg SaveRunParams) error {
	_, err := q.db.Exec(ctx, saveRun,
		arg.ID,
		arg.Status,
		arg.Observation,
		arg.ExecutionStartedAt,
		arg.DeadlineAt,
		arg.FinishedAt,
		arg.CancelRequestedAt,
		arg.CancelAttemptedAt,
		arg.StopReason,
		arg.StopMethod,
		arg.Error,
		arg.NativeTurnID,
		arg.NextDeliveryNumber,
		arg.FinalMessageID,
		arg.Phase,
		arg.AgentStatus,
		arg.AgentError,
	)
	return err
}

const saveSession = `-- name: SaveSession :exec
UPDATE sessions
SET sandbox_state = $2,
    sandbox_last_known_state = $3,
    sandbox_error = $4,
    sandbox_id = $5,
    process_id = $6,
    launch_id = $7,
    thread_id = $8,
    history_path = $9,
    history_offset = $10,
    workspace = $11,
    harness_home = $12,
    slot_reserved = $13,
    next_run_number = $14,
    next_event_sequence = $15
WHERE id = $1
`

type SaveSessionParams struct {
	ID                    uuid.UUID      `json:"id"`
	SandboxState          string         `json:"sandbox_state"`
	SandboxLastKnownState *string        `json:"sandbox_last_known_state"`
	SandboxError          *session.Error `json:"sandbox_error"`
	SandboxID             *string        `json:"sandbox_id"`
	ProcessID             *int           `json:"process_id"`
	LaunchID              *uuid.UUID     `json:"launch_id"`
	ThreadID              *string        `json:"thread_id"`
	HistoryPath           *string        `json:"history_path"`
	HistoryOffset         int64          `json:"history_offset"`
	Workspace             *string        `json:"workspace"`
	HarnessHome           *string        `json:"harness_home"`
	SlotReserved          bool           `json:"slot_reserved"`
	NextRunNumber         int            `json:"next_run_number"`
	NextEventSequence     int64          `json:"next_event_sequence"`
}

func (q *Queries) SaveSession(ctx context.Context, arg SaveSessionParams) error {
	_, err := q.db.Exec(ctx, saveSession,
		arg.ID,
		arg.SandboxState,
		arg.SandboxLastKnownState,
		arg.SandboxError,
		arg.SandboxID,
		arg.ProcessID,
		arg.LaunchID,
		arg.ThreadID,
		arg.HistoryPath,
		arg.HistoryOffset,
		arg.Workspace,
		arg.HarnessHome,
		arg.SlotReserved,
		arg.NextRunNumber,
		arg.NextEventSequence,
	)
	return err
}

const tryWorkerLock = `-- name: TryWorkerLock :one
SELECT pg_try_advisory_lock($1::bigint)
`

func (q *Queries) TryWorkerLock(ctx context.Context, lockKey int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryWorkerLock, lockKey)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}

const upsertMessage = `-- name: UpsertMessage :exec
INSERT INTO messages(id, session_id, run_id, role, kind, text, delivery_status, delivery_number, error, native_key, registered_sequence, position, created_at, external_key)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT(id) DO UPDATE SET kind = EXCLUDED.kind,
    text = EXCLUDED.text,
    delivery_status = EXCLUDED.delivery_status,
    error = EXCLUDED.error,
    native_key = EXCLUDED.native_key,
    position = EXCLUDED.position
`

type UpsertMessageParams struct {
	ID                 uuid.UUID         `json:"id"`
	SessionID          uuid.UUID         `json:"session_id"`
	RunID              uuid.UUID         `json:"run_id"`
	Role               string            `json:"role"`
	Kind               *string           `json:"kind"`
	Text               string            `json:"text"`
	DeliveryStatus     *string           `json:"delivery_status"`
	DeliveryNumber     *int              `json:"delivery_number"`
	Error              *session.Error    `json:"error"`
	NativeKey          *string           `json:"native_key"`
	RegisteredSequence int64             `json:"registered_sequence"`
	Position           *session.Position `json:"position"`
	CreatedAt          time.Time         `json:"created_at"`
	ExternalKey        *string           `json:"external_key"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) error {
	_, err := q.db.Exec(ctx, upsertMessage,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.Role,
		arg.Kind,
		arg.Text,
		arg.DeliveryStatus,
		arg.DeliveryNumber,
		arg.Error,
		arg.NativeKey,
		arg.RegisteredSequence,
		arg.Position,
		arg.CreatedAt,
		arg.ExternalKey,
	)
	return err
}

const upsertTool = `-- name: UpsertTool :exec
INSERT INTO tool_calls(id, session_id, run_id, name, input, status, result, output_completeness, truncation_reason, native_key, registered_sequence, position, created_at, result_digest)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT(id) DO UPDATE SET name = EXCLUDED.name,
    input = EXCLUDED.input,
    status = EXCLUDED.status,
    result = EXCLUDED.result,
    result_digest = EXCLUDED.result_digest,
    output_completeness = EXCLUDED.output_completeness,
    truncation_reason = EXCLUDED.truncation_reason,
    position = EXCLUDED.position
`

type UpsertToolParams struct {
	ID                 uuid.UUID         `json:"id"`
	SessionID          uuid.UUID         `json:"session_id"`
	RunID              uuid.UUID         `json:"run_id"`
	Name               string            `json:"name"`
	Input              json.RawMessage   `json:"input"`
	Status             string            `json:"status"`
	Result             json.RawMessage   `json:"result"`
	OutputCompleteness string            `json:"output_completeness"`
	TruncationReason   *string           `json:"truncation_reason"`
	NativeKey          *string           `json:"native_key"`
	RegisteredSequence int64             `json:"registered_sequence"`
	Position           *session.Position `json:"position"`
	CreatedAt          time.Time         `json:"created_at"`
	ResultDigest       string            `json:"result_digest"`
}

func (q *Queries) UpsertTool(ctx context.Context, arg UpsertToolParams) error {
	_, err := q.db.Exec(ctx, upsertTool,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.Name,
		arg.Input,
		arg.Status,
		arg.Result,
		arg.OutputCompleteness,
		arg.TruncationReason,
		arg.NativeKey,
		arg.RegisteredSequence,
		arg.Position,
		arg.CreatedAt,
		arg.ResultDigest,
	)
	return err
}
