// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const runsByNativeIDs = `-- name: RunsByNativeIDs :many
SELECT id, session_id, number, status, observation, created_at, execution_started_at, deadline_at, finished_at, cancel_requested_at, cancel_attempted_at, stop_reason, stop_method, error, native_turn_id, next_delivery_number, final_message_id, input_fingerprint, env_ciphertext, env_names, env_from, phase, agent_status, agent_error, input_tokens, output_tokens, total_tokens FROM runs WHERE session_id = $1 AND native_turn_id = ANY($2::text[]) ORDER BY number
`

type RunsByNativeIDsParams struct {
	SessionID uuid.UUID `json:"session_id"`
	TurnIds   []string  `json:"turn_ids"`
}

func (q *Queries) RunsByNativeIDs(ctx context.Context, arg RunsByNativeIDsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, runsByNativeIDs, arg.SessionID, arg.TurnIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Number,
			&i.Status,
			&i.Observation,
			&i.CreatedAt,
			&i.ExecutionStartedAt,
			&i.DeadlineAt,
			&i.FinishedAt,
			&i.CancelRequestedAt,
			&i.CancelAttemptedAt,
			&i.StopReason,
			&i.StopMethod,
			&i.Error,
			&i.NativeTurnID,
			&i.NextDeliveryNumber,
			&i.FinalMessageID,
			&i.InputFingerprint,
			&i.EnvCiphertext,
			&i.EnvNames,
			&i.EnvFrom,
			&i.Phase,
			&i.AgentStatus,
			&i.AgentError,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
