"""Account credentials move only between S3 and the sandbox, never PostgreSQL."""

import asyncio
import hashlib
import json
import logging
from typing import Any

import boto3
from agentbox import AsyncSandbox
from botocore.config import Config

from orpheus.configuration import Credentials
from orpheus.errors import ExecutionError

logger = logging.getLogger(__name__)
MAX_AUTH_BYTES = 1024 * 1024


def validate_auth(raw: bytes) -> bytes:
    if len(raw) > MAX_AUTH_BYTES:
        raise ValueError("Credentials file is too large")
    value = json.loads(raw)
    tokens = value.get("tokens") if isinstance(value, dict) else None
    if not isinstance(tokens, dict) or not all(
        isinstance(tokens.get(key), str) and tokens[key]
        for key in ("access_token", "refresh_token", "id_token")
    ):
        raise ValueError("Invalid account credentials")
    return raw


class AccountCredentials:
    def __init__(self, sandbox: AsyncSandbox, home: str, source: Credentials):
        assert source.store and source.key
        self.sandbox, self.home, self.source = sandbox, home, source
        self.digest: bytes | None = None
        self.dirty = True
        self.watcher: Any = None
        self.watch_token: object | None = None
        self.client = boto3.client(
            "s3",
            region_name=source.store.region,
            endpoint_url=source.store.endpoint_url,
            config=Config(
                connect_timeout=5, read_timeout=10, retries={"max_attempts": 1}
            ),
        )

    async def seed(self) -> None:
        def read() -> bytes:
            assert self.source.store
            response = self.client.get_object(
                Bucket=self.source.store.bucket, Key=self.source.key
            )
            try:
                return validate_auth(response["Body"].read(MAX_AUTH_BYTES + 1))
            finally:
                response["Body"].close()

        try:
            raw = await asyncio.to_thread(read)
            await self.sandbox.files.write(f"{self.home}/auth.json", raw, user="user")
            # The home path is generated by Orpheus, never a client argument.
            import shlex

            await self.sandbox.commands.run(
                "chmod 600 " + shlex.quote(f"{self.home}/auth.json"), user="user"
            )
            self.digest = hashlib.sha256(raw).digest()
        except Exception:  # noqa: BLE001 - normalize storage/SDK errors without leaking credentials
            raise ExecutionError(
                "credentials_unavailable", "Account credentials are unavailable."
            ) from None

    async def watch(self) -> None:
        if self.watcher is not None:
            return
        token = self.watch_token = object()

        async def changed(event) -> None:
            if "auth.json" in str(getattr(event, "name", "")) or "auth.json" in str(
                getattr(event, "path", "")
            ):
                self.dirty = True

        async def exited(error) -> None:
            if self.watch_token is token:
                self.dirty = True
                self.watcher = None
                self.watch_token = None

        watcher = await self.sandbox.files.watch_dir(
            self.home, on_event=changed, on_exit=exited, user="user", timeout=0
        )
        if self.watch_token is token:
            self.watcher = watcher
        else:
            await watcher.stop()
        self.dirty = True

    async def sync(self, *, force: bool = False) -> None:
        if not force and not self.dirty and self.watcher is not None:
            return
        self.dirty = False
        try:
            if self.watcher is None:
                await self.watch()
                self.dirty = False
            for attempt in range(3):
                try:
                    raw = await self.sandbox.files.read(
                        f"{self.home}/auth.json", format="bytes", user="user"
                    )
                    raw = bytes(raw)
                    validate_auth(raw)
                    break
                except ValueError, UnicodeError:
                    if attempt == 2:
                        raise
                    await asyncio.sleep(0.1)
            digest = hashlib.sha256(raw).digest()
            if digest == self.digest:
                return
            assert self.source.store
            await asyncio.to_thread(
                self.client.put_object,
                Bucket=self.source.store.bucket,
                Key=self.source.key,
                Body=raw,
                ContentType="application/json",
            )
            self.digest = digest
        except Exception as error:  # noqa: BLE001 - upload failure must not block pause
            # Do not retain auth sync status or retry jobs in the application DB.
            logger.warning(
                "Account credential upload failed (%s)", type(error).__name__
            )

    async def close(self) -> None:
        self.watch_token = None
        watcher, self.watcher = self.watcher, None
        if watcher:
            await watcher.stop()
        self.client.close()
